/**
 * The wire protocol for the control API.
 *
 * The viewer, the server and the CLI all import from here and nowhere else:
 * this is the single definition of what a command is, what comes back, and what
 * either side is allowed to assume. Everything is a zod schema with its type
 * inferred from it, so validation and the type can never say different things.
 */

export {
  avatarCommandSchema,
  backdropCommandSchema,
  type CameraFrame,
  type Command,
  type CommandName,
  cameraCommandSchema,
  cameraFrameSchema,
  clearCommandSchema,
  commandSchema,
  debugCommandSchema,
  deckCommandSchema,
  emotionCommandSchema,
  emotionNameSchema,
  emotionVectorSchema,
  expressionCommandSchema,
  fingerNameSchema,
  gestureCommandSchema,
  hopCommandSchema,
  idleCommandSchema,
  interruptCommandSchema,
  lookCommandSchema,
  overlayCommandSchema,
  parseCommand,
  performCommandSchema,
  placeCommandSchema,
  placementSchema,
  pointCommandSchema,
  queueCommandSchema,
  resetCommandSchema,
  roomCommandSchema,
  type Shot,
  sayCommandSchema,
  sideSchema,
  slideCommandSchema,
  slidePlacementSchema,
  type TuningPatch,
  type TurnRequest,
  tuneCommandSchema,
  turnSchema,
  type VoiceDsp,
  voiceCommandSchema,
  voiceDspSchema,
  wearCommandSchema,
} from './commands';
export {
  type CommandRequest,
  type CommandResponse,
  commandRequestSchema,
  commandResponseSchema,
  type Deck,
  type DecksResponse,
  type DeckTextResponse,
  deckSchema,
  decksResponseSchema,
  deckTextResponseSchema,
  type EventsResponse,
  eventsResponseSchema,
  type HistoryEntry,
  type HistoryResponse,
  historyEntrySchema,
  historyResponseSchema,
  type LabelledId,
  labelledIdSchema,
  localizedSchema,
  type PlacementReport,
  placementReportSchema,
  type QueueAdd,
  type QueueEntry,
  type QueueResponse,
  type QueueRewind,
  type QueueUpdate,
  queueAddSchema,
  queueEntrySchema,
  queueResponseSchema,
  queueRewindSchema,
  queueUpdateSchema,
  type ReportBody,
  reportBodySchema,
  type SessionEvent,
  type SessionState,
  type SlideReport,
  type Snapshot,
  type SpeechState,
  type StreamMessage,
  sessionEventSchema,
  sessionEventTypeSchema,
  sessionStateSchema,
  slideReportSchema,
  snapshotSchema,
  speechStateSchema,
  streamMessageSchema,
  type Tuning,
  tuningSchema,
  type Vocabulary,
  type VoiceReport,
  vocabularySchema,
  voiceReportSchema,
} from './messages';
